remove border its no longer used
ran html validator on the acp page and noticed this
Warning: The border attribute is obsolete. Consider specifying img { border: 0; } in CSS instead.
Error: No space between attributes.